apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-azure-hdd-xfs
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  cachingMode: ReadOnly
  fsType: xfs
  skuName: Standard_LRS
  zoned: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-azure-ssd-xfs
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  cachingMode: ReadOnly
  fsType: xfs
  skuName: StandardSSD_LRS
  zoned: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-azure-premium-xfs
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  cachingMode: ReadOnly
  fsType: xfs
  skuName: Premium_LRS
  zoned: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-azure-premium-2-xfs
provisioner: kubernetes.io/azure-disk
parameters:
  fsType: xfs
  kind: Managed
  cachingMode: None
  skuName: PremiumV2_LRS
  perfProfile: Basic
  # enableBursting: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
# allowedTopologies:
# - matchLabelExpressions:
#   - key: topology.disk.csi.azure.com/zone
#     values:
#     - azure
