apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:azure-cloud-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:azure-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: azure-cloud-controller-manager
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:azure-cloud-controller-manager:extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: azure-cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cloud-controller-manager
  namespace: kube-system
  labels:
    component: azure-cloud-controller-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: control-plane
      component: azure-cloud-controller-manager
  template:
    metadata:
      labels:
        tier: control-plane
        component: azure-cloud-controller-manager
    spec:
      priorityClassName: system-cluster-critical
      hostNetwork: true
      serviceAccountName: azure-cloud-controller-manager
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
        node.cloudprovider.kubernetes.io/platform: azure
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
      containers:
        - name: azure-cloud-controller-manager
          image: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.26.5
          imagePullPolicy: IfNotPresent
          command: ["cloud-controller-manager"]
          args:
            - --v=2
            - --cluster-name=$(CLUSTER_NAME)
            - --cloud-config=/etc/azure/azure.json
            - --cloud-provider=azure
            - --allocate-node-cidrs=false
            - --controllers=cloud-node-lifecycle # disable cloud-node controller
            - --configure-cloud-routes=false
            - --leader-elect-resource-name=cloud-controller-manager-azure
            - --use-service-account-credentials
            # - --bind-address=127.0.0.1
            - --secure-port=10267
          env:
            - name: CLUSTER_NAME
              value: kubernetes
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10267
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: cloud-config
              mountPath: /etc/azure
              readOnly: true
      volumes:
        - name: cloud-config
          secret:
            secretName: azure-managed-identity
