apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azuredisk
  namespace: default
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-azuredisk
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node.cloudprovider.kubernetes.io/platform: azure
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: statefulset-azuredisk
          image: ubuntu
          command: ["sleep","6000"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/azuredisk
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-azure-ssd-xfs
