apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.scaleway.com
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: File
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: scw-bssd
provisioner: csi.scaleway.com
parameters:
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: scw-bssd-enc
provisioner: csi.scaleway.com
parameters:
  csi.storage.k8s.io/fstype: xfs
  csi.storage.k8s.io/node-stage-secret-name: "scw-csi-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
