apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-scaleway
  namespace: default
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-scaleway
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
      containers:
        - name: statefulset-scaleway
          image: ubuntu
          command: ["sleep","6000"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/scaleway
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: scw-bssd
