apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-oracle
  namespace: default
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-oracle
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node.cloudprovider.kubernetes.io/platform: oracle
      # tolerations:
      #   - operator: Exists
      containers:
        - name: statefulset-oracle
          image: ubuntu
          command: ["sleep","6000"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/oracle
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: oci-bv
