apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-openstack
  namespace: default
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-openstack
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        node.cloudprovider.kubernetes.io/platform: openstack
      tolerations:
        - operator: Exists
      containers:
        - name: statefulset-openstack
          image: ubuntu
          command: ["sleep","6000"]
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/openstack
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-cinder-high-speed-xfs
